name: Deploy Astro to OVH via SFTP (password)

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Astro site
        run: npm run build

      - name: Deploy to OVH via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.FABRLT_FTP_LOGIN }}
          server: ${{ secrets.FABRLT_FTP_SERVER }}
          local_path: './dist/*'
          remote_path: './'
          port: 22
          sftp_only: true
          password: ${{ secrets.FABRLT_FTP_PASSWORD }}