name: Deploy Astro to OVH via SFTP (password)

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Astro site
        run: npm run build

      - name: Deploy to OVH via SFTP (password)
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FABRLT_FTP_USERNAME_URL }}
          username: ${{ secrets.FABRLT_FTP_LOGIN }}
          password: ${{ secrets.FABRLT_FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /www/
          port: 22
          protocol: sftp